drop_features:
- ATA
- SAMPLE_ID
- AIR_TEMPERATURE
- U_WIND
- V_WIND
categorical_features:
- ARI_PO
selected_features:
- DIST
- PORT_SIZE
- ARI_PO
- DEADWEIGHT
- GT
- LENGTH
- DIST_log
- DIST_dev
- DIST_RATIO
- DIST_RATIO2
- DIST_RATIO3