drop_features:
- ATA
- SAMPLE_ID
categorical_features:
- SHIP_TYPE_CATEGORY
- ARI_CO
- ARI_PO
- FLAG
selected_features:
- DIST
- BDI_ADJ
- month
- PORT_SIZE
- BRENT
- weekday
- WTI
- year
- SHIP_TYPE_CATEGORY
- ARI_CO
- DUBAI
- DEADWEIGHT
- BUILT
- day
- ARI_PO
- LENGTH
- GT
- AIR_TEMPERATURE
- FLAG
