drop_features:
- ATA
- SAMPLE_ID
- AIR_TEMPERATURE
- U_WIND
- V_WIND
categorical_features:
- SHIP_TYPE_CATEGORY
- ARI_CO
- ARI_PO
- FLAG
selected_features:
- DIST
- PORT_SIZE
- weekday
- SHIP_TYPE_CATEGORY
- ARI_CO
- DEADWEIGHT
- year
- BUILT
- ARI_PO
- DIST_diff1
- LENGTH
- GT
- FLAG
- month
- BN
