name: challenge
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10.11
  - pip
  - pip:
    - black
    - flake8
    - isort
    - catboost==1.2
    - category-encoders==2.2.2
    - hydra-core==1.3.1
    - lightgbm==3.3.5
    - pytorch-forecasting==0.9.0
    - pytorch-lightning==1.3.6
    - pytorch-tabnet==3.0.0
    - pytorch-tabular==0.7.0
    - matplotlib==3.7.1
    - numpy==1.23.5
    - optuna==2.10.1
    - pandas==1.1.5
    - plotly==5.15.0
    - prettytable==3.8.0
    - scikit-learn==0.24.2
    - scipy==1.10.1
    - torch==1.13.1
    - tqdm==4.65.0
    - wandb==0.15.8
    - xgboost==1.7.6
    - seaborn==0.12.2
    - shap==0.42.1