defaults:
  - _self_
  - data: dataset
  - models: lightgbm
  - store: features
  - experiment: wandb
  - hydra: custom
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

output:
  path: output
  name: median-final-ensemble.csv
  submit: sample_submission.csv

median_preds:
  - 5fold-mae-catboost.csv
  - 5fold-mae-lightgbm.csv
  - 5fold-tweedie-lightgbm.csv
  - 5fold-regression-tabnet.csv